### ISSUE TITLE
Missing author

### ISSUE THREAD

**Issue by chandanadesilva** [springframeworkguru/spring5webapp#6]
https://github.com/springframeworkguru/spring5webapp/blob/0b8c61ef3bc2fbdc3c54a0dde5753d28b4372ac2/src/main/java/guru/springframework/spring5webapp/bootstrap/DevBootstrap.java#L45

There is a missing step to add rod to the noEJB book 
  noEJB.getAuthors().add(rod);

**Comment by springframeworkguru** [comment]
Please comment in the course for support.
